### ISSUE TITLE
Pictures in teams section are unavailable

### ISSUE THREAD

**Issue by Saakshaat** [dsc-umass/umass-dsc-website#10]
The avatars for everyone except Abhinav and Prof Davila are unavailabe on the Team section of the website.

![Screen Shot 2020-02-03 at 1 55 03 PM](https://user-images.githubusercontent.com/49038287/73681678-e0da7380-468c-11ea-85a3-caa93f4c6c59.png)

**Comment by abhinavtripathy** [comment]
Fixed in "Fix" PR
